version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - cadmusnetwork

  mongoseed:
    build: ./MongoSeed
    depends_on:
      - mongo
    networks:
      - cadmusnetwork

  cadmusapi:
    image: naftis/fusi:cadmusapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 60304:60304
    depends_on:
      - mongo
      - mongoseed
    networks:
      - cadmusnetwork

networks:
  cadmusnetwork:
    driver: bridge
