version: '3.4'

services:
  # MongoDB
  cadmusmongo:
    image: mongo
    container_name: cadmusmongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - cadmusnetwork
    
  mongo-seed:
    build: ./MongoSeed
    depends_on:
      - cadmusmongo

  cadmusapi:
    image: naftis/fusi:cadmusapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 60304:60304
    depends_on:
      - cadmusmongo
    networks:
      - cadmusnetwork

networks:
  cadmusnetwork:
    driver: bridge
