version: '3.4'

services:
  # MongoDB
  cadmus-mongo:
    image: mongo
    container_name: cadmus-mongo
    ports:
      - 27017:27017
    networks:
      - cadmus-network
  
  # Cadmus API
  cadmus-api:
    image: naftis/fusi:cadmusapi
    ports:
      - 60304:60304
    depends_on:
      - cadmus-mongo
    build:
      context: .
      dockerfile: CadmusApi/Dockerfile
    networks:
      - cadmus-network

networks:
  cadmus-network:
    driver: bridge
